wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: huggingface
    huggingface_version: 4.23.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1666849712.453506
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.10.6
      5: 0.13.4
      6: 4.23.1
      8:
      - 5
batch_size:
  desc: null
  value: 16
category:
  desc: null
  value: null
clip:
  desc: null
  value: false
data_dir:
  desc: null
  value: ../dataset/
epochs:
  desc: null
  value: 10
factor:
  desc: null
  value: 0.1
heads:
  desc: null
  value: 12
hidden_dropout_prob:
  desc: null
  value: 0.3
hidden_size:
  desc: null
  value: 312
image_size:
  desc: null
  value: 224
lr:
  desc: null
  value: 0.0001
max_position_embeddings:
  desc: null
  value: 28
mixed_precision:
  desc: null
  value: true
model_dir:
  desc: null
  value: ../out/weights/val_loss_3.pt
n_layers:
  desc: null
  value: 4
num_vis:
  desc: null
  value: 64
num_workers:
  desc: null
  value: 4
patience:
  desc: null
  value: 10
run_name:
  desc: null
  value: bench_mark1
save_dir:
  desc: null
  value: ../out/weights/benchmark1
seed:
  desc: null
  value: 42
smoothing:
  desc: null
  value: null
test_pct:
  desc: null
  value: 1.0
train_pct:
  desc: null
  value: 1.0
type_vocab_size:
  desc: null
  value: 2
use_pretrained:
  desc: null
  value: false
valid_pct:
  desc: null
  value: 1.0
vocab_size:
  desc: null
  value: 30522
